# Generated by Django 5.0.2 on 2024-02-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_group',
        ),
    ]
